/* ============================================ */
/* FILE: js/flashcard-tech.js                    */
/* DESKRIPSI: 90+ Kosakata Teknik untuk Flashcard*/
/* SIMPAN DI: quiz-engine/js/                    */
/* ============================================ */

const TECH_TERMS = [
  // ========== KESELAMATAN KERJA (安全衛生) ==========
  { kanji: "電気器具", reading: "でんききぐ", meaning: "Peralatan listrik", category: "安全衛生" },
  { kanji: "漏電", reading: "ろうでん", meaning: "Kebocoran arus listrik", category: "安全衛生" },
  { kanji: "感電", reading: "かんでん", meaning: "Sengatan listrik", category: "安全衛生" },
  { kanji: "接地", reading: "せっち", meaning: "Grounding / Pembumian", category: "安全衛生" },
  { kanji: "危険予知", reading: "きけんよち", meaning: "Prediksi bahaya (KYT)", category: "安全衛生" },
  { kanji: "危険", reading: "きけん", meaning: "Bahaya / Hazard", category: "安全衛生" },
  { kanji: "安全衛生", reading: "あんぜんえいせい", meaning: "Keselamatan & Kesehatan Kerja", category: "安全衛生" },
  { kanji: "労働安全衛生法", reading: "ろうどうあんぜんえいせいほう", meaning: "Undang-Undang Keselamatan dan Kesehatan Kerja", category: "安全衛生" },
  { kanji: "労働災害", reading: "ろうどうさいがい", meaning: "Kecelakaan kerja", category: "安全衛生" },
  { kanji: "整理整頓", reading: "せいりせいとん", meaning: "Rapi & teratur (bagian dari 5S)", category: "安全衛生" },
  { kanji: "照度", reading: "しょうど", meaning: "Iluminasi / Tingkat pencahayaan (lux)", category: "安全衛生" },
  { kanji: "避難", reading: "ひなん", meaning: "Evakuasi / Mengungsi", category: "安全衛生" },
  { kanji: "火気厳禁", reading: "かきげんきん", meaning: "Dilarang menggunakan api", category: "安全衛生" },
  { kanji: "保護具", reading: "ほごぐ", meaning: "Alat Pelindung Diri (APD)", category: "安全衛生" },
  { kanji: "玉掛け", reading: "たまがけ", meaning: "Rigging / Slinging (mengikat beban)", category: "安全衛生" },
  { kanji: "遮光", reading: "しゃこう", meaning: "Pelindung / Penahan cahaya", category: "安全衛生" },
  { kanji: "防塵", reading: "ぼうじん", meaning: "Anti debu / Tahan debu", category: "安全衛生" },
  { kanji: "袖まくり", reading: "そでまくり", meaning: "Lengan digulung (berbahaya saat kerja panas)", category: "安全衛生" },
  { kanji: "軍手", reading: "ぐんて", meaning: "Sarung tangan katun (mudah terbakar)", category: "安全衛生" },
  { kanji: "皮手袋", reading: "かわてぶくろ", meaning: "Sarung tangan kulit (tahan panas)", category: "安全衛生" },
  { kanji: "安全作業", reading: "あんぜんさぎょう", meaning: "Pekerjaan yang aman / Safety work", category: "安全衛生" },
  { kanji: "点検", reading: "てんけん", meaning: "Inspeksi / Pemeriksaan", category: "安全衛生" },
  { kanji: "異常音", reading: "いじょうおん", meaning: "Suara abnormal / Aneh", category: "安全衛生" },
  { kanji: "耳栓", reading: "みみせん", meaning: "Earplug / Penutup telinga", category: "安全衛生" },

  // ========== QUALITY CONTROL (品質管理) ==========
  { kanji: "品質管理", reading: "ひんしつかんり", meaning: "Pengendalian mutu / Quality Control", category: "品質管理" },
  { kanji: "不良品", reading: "ふりょうひん", meaning: "Produk cacat / Reject", category: "品質管理" },
  { kanji: "不適合品", reading: "ふてきごうひん", meaning: "Produk non-conforming / Tidak sesuai", category: "品質管理" },
  { kanji: "検査", reading: "けんさ", meaning: "Inspeksi / Pemeriksaan", category: "品質管理" },
  { kanji: "全数検査", reading: "ぜんすうけんさ", meaning: "Inspeksi 100% (semua diperiksa)", category: "品質管理" },
  { kanji: "抜取検査", reading: "ぬきとりけんさ", meaning: "Inspeksi sampling (acak)", category: "品質管理" },
  { kanji: "非破壊検査", reading: "ひはかいけんさ", meaning: "NDT / Uji tanpa merusak", category: "品質管理" },
  { kanji: "破壊検査", reading: "はかいけんさ", meaning: "Uji merusak / Destructive test", category: "品質管理" },
  { kanji: "超音波探傷試験", reading: "ちょうおんぱたんしょうしけん", meaning: "Uji ultrasonik (NDT)", category: "品質管理" },
  { kanji: "外観検査", reading: "がいかんけんさ", meaning: "Inspeksi visual / Tampak luar", category: "品質管理" },
  { kanji: "特性要因図", reading: "とくせいよういんず", meaning: "Diagram tulang ikan / Fishbone (Ishikawa)", category: "品質管理" },
  { kanji: "散布図", reading: "さんぷず", meaning: "Diagram pencar / Scatter diagram", category: "品質管理" },
  { kanji: "管理図", reading: "かんりず", meaning: "Diagram kendali / Control chart", category: "品質管理" },
  { kanji: "ヒストグラム", reading: "ひすとぐらむ", meaning: "Histogram (grafik batang distribusi)", category: "品質管理" },
  { kanji: "パレート図", reading: "ぱれーとず", meaning: "Diagram Pareto (prioritas 80/20)", category: "品質管理" },
  { kanji: "チェックシート", reading: "ちぇっくしーと", meaning: "Lembar periksa / Check sheet", category: "品質管理" },
  { kanji: "層別", reading: "そうべつ", meaning: "Stratifikasi / Pengelompokan data", category: "品質管理" },
  { kanji: "累積比率", reading: "るいせきひりつ", meaning: "Persentase kumulatif", category: "品質管理" },
  { kanji: "QC工程表", reading: "QCこうていひょう", meaning: "Tabel proses QC (rencana kendali mutu)", category: "品質管理" },
  { kanji: "三現主義", reading: "さんげんしゅぎ", meaning: "Prinsip 3-Gen (Genba, Genbutsu, Genjitsu)", category: "品質管理" },
  { kanji: "現場", reading: "げんば", meaning: "Lokasi aktual / Tempat kejadian", category: "品質管理" },
  { kanji: "現物", reading: "げんぶつ", meaning: "Barang aktual / Benda nyata", category: "品質管理" },
  { kanji: "現実", reading: "げんじつ", meaning: "Fakta aktual / Kenyataan", category: "品質管理" },

  // ========== PENGUKURAN (測定) ==========
  { kanji: "測定", reading: "そくてい", meaning: "Pengukuran", category: "測定" },
  { kanji: "測定器", reading: "そくていき", meaning: "Alat ukur", category: "測定" },
  { kanji: "測定面", reading: "そくていめん", meaning: "Permukaan ukur", category: "測定" },
  { kanji: "最小読取値", reading: "さいしょうよみとりち", meaning: "Nilai pembacaan terkecil / Resolusi", category: "測定" },
  { kanji: "校正", reading: "こうせい", meaning: "Kalibrasi", category: "測定" },
  { kanji: "零点", reading: "れいてん", meaning: "Titik nol / Zero point", category: "測定" },
  { kanji: "外径", reading: "がいけい", meaning: "Diameter luar", category: "測定" },
  { kanji: "内径", reading: "ないけい", meaning: "Diameter dalam", category: "測定" },
  { kanji: "膜厚", reading: "まくあつ", meaning: "Ketebalan lapisan / Film thickness", category: "測定" },
  { kanji: "膜厚計", reading: "まくあつけい", meaning: "Alat ukur ketebalan lapisan", category: "測定" },
  { kanji: "平行度", reading: "へいこうど", meaning: "Parallelism / Kesejajaran", category: "測定" },
  { kanji: "本尺", reading: "ほんしゃく", meaning: "Skala utama (jangka sorong)", category: "測定" },
  { kanji: "副尺", reading: "ふくしゃく", meaning: "Skala nonius / Vernier", category: "測定" },
  { kanji: "シリンダーゲージ", reading: "しりんだーげーじ", meaning: "Cylinder gauge (untuk diameter dalam)", category: "測定" },
  { kanji: "ダイヤルゲージ", reading: "だいやるげーじ", meaning: "Dial gauge (alat ukur perbandingan)", category: "測定" },

  // ========== MATERIAL & PROSES (材料・加工) ==========
  { kanji: "弾性", reading: "だんせい", meaning: "Elastisitas (kembali ke bentuk semula)", category: "材料" },
  { kanji: "塑性", reading: "そせい", meaning: "Plastisitas (tidak kembali ke bentuk semula)", category: "材料" },
  { kanji: "破壊", reading: "はかい", meaning: "Pecah / Rusak / Destruksi", category: "材料" },
  { kanji: "引張試験", reading: "ひっぱりしけん", meaning: "Uji tarik / Tensile test", category: "材料" },
  { kanji: "曲げ試験", reading: "まげしけん", meaning: "Uji tekuk / Bend test", category: "材料" },
  { kanji: "衝撃試験", reading: "しょうげきしけん", meaning: "Uji impak / Impact test", category: "材料" },
  { kanji: "曲げ加工", reading: "まげかこう", meaning: "Proses penekukan / Bending", category: "材料" },
  { kanji: "溶接", reading: "ようせつ", meaning: "Pengelasan / Welding", category: "材料" },
  { kanji: "塗装", reading: "とそう", meaning: "Pengecatan / Coating", category: "材料" },
  { kanji: "塗膜", reading: "とまく", meaning: "Lapisan cat / Paint film", category: "材料" },
  { kanji: "鋼板", reading: "こうはん", meaning: "Plat baja / Steel plate", category: "材料" },
  { kanji: "天然ゴム", reading: "てんねんごむ", meaning: "Karet alam (isolator)", category: "材料" },
  { kanji: "絶縁", reading: "ぜつえん", meaning: "Isolasi / Insulation", category: "材料" },
  { kanji: "導体", reading: "どうたい", meaning: "Konduktor / Penghantar", category: "材料" },
  { kanji: "荷重", reading: "かじゅう", meaning: "Beban / Load", category: "材料" },
  { kanji: "破損", reading: "はそん", meaning: "Kerusakan / Pecah", category: "材料" },
  { kanji: "劣化", reading: "れっか", meaning: "Degradasi / Penurunan mutu", category: "材料" },
  { kanji: "円筒", reading: "えんとう", meaning: "Silinder / Tabung", category: "材料" },
  { kanji: "円周率", reading: "えんしゅうりつ", meaning: "Pi (π) / Konstanta lingkaran ≈ 3.14", category: "材料" },

  // ========== DOKUMEN & GAMBAR TEKNIK (図面) ==========
  { kanji: "組立図", reading: "くみたてず", meaning: "Gambar assembly / Perakitan", category: "図面" },
  { kanji: "展開図", reading: "てんかいず", meaning: "Gambar bentangan / Development drawing", category: "図面" },
  { kanji: "製図", reading: "せいず", meaning: "Menggambar teknik / Drafting", category: "図面" },
  { kanji: "第三角法", reading: "だいさんかくほう", meaning: "Proyeksi sudut ketiga (Third Angle)", category: "図面" },
  { kanji: "第一角法", reading: "だいいちかくほう", meaning: "Proyeksi sudut pertama (First Angle)", category: "図面" },
  { kanji: "図面", reading: "ずめん", meaning: "Gambar teknik / Drawing", category: "図面" },
  { kanji: "寸法", reading: "すんぽう", meaning: "Dimensi / Ukuran", category: "図面" },
  { kanji: "公差", reading: "こうさ", meaning: "Toleransi", category: "図面" },
  { kanji: "はめあい", reading: "はめあい", meaning: "Suaian / Fit (poros-lubang)", category: "図面" },
  { kanji: "表面性状", reading: "ひょうめんせいじょう", meaning: "Kekasaran permukaan / Surface texture", category: "図面" },
  { kanji: "かくれ線", reading: "かくれせん", meaning: "Garis tersembunyi / Hidden line", category: "図面" },
  { kanji: "中心線", reading: "ちゅうしんせん", meaning: "Garis sumbu / Center line", category: "図面" },
  { kanji: "寸法線", reading: "すんぽうせん", meaning: "Garis dimensi", category: "図面" },
  { kanji: "等角投影図", reading: "とうかくとうえいず", meaning: "Gambar isometrik", category: "図面" },

  // ========== MANAJEMEN & LAINNYA ==========
  { kanji: "予防保全", reading: "よぼうほぜん", meaning: "Pemeliharaan pencegahan / Preventive maintenance", category: "保全" },
  { kanji: "日常点検", reading: "にちじょうてんけん", meaning: "Inspeksi harian / Daily check", category: "保全" },
  { kanji: "定期検査", reading: "ていきけんさ", meaning: "Pemeriksaan berkala / Periodic inspection", category: "保全" },
  { kanji: "ＰＤＣＡ", reading: "ぴーでぃーしーえー", meaning: "Plan-Do-Check-Act (siklus perbaikan)", category: "品質管理" },
  { kanji: "３Ｒ", reading: "さんあーる", meaning: "Reduce, Reuse, Recycle", category: "環境" },
  { kanji: "不良率", reading: "ふりょうりつ", meaning: "Tingkat cacat / Defect rate", category: "品質管理" },
  { kanji: "周速度", reading: "しゅうそくど", meaning: "Kecepatan keliling / Peripheral speed", category: "機械加工" },
  { kanji: "切削", reading: "せっさく", meaning: "Pemotongan / Cutting", category: "機械加工" },
];

console.log('📦 Tech Terms loaded: ' + TECH_TERMS.length + ' items');